# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo-secret
# type: kubernetes.io/basic-auth
# stringData:
#   password: test1234
apiVersion: v1
data:
  password: cGFzc3dvcmQxMjM= #password123
  username: YWRtaW51c2Vy #adminuser
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-creds