apiVersion: v1
kind: Service
metadata:
  name: admin-panel
  labels:
    name: admin-panel
    app: admin-app-panel
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: admin-app-pod
    app: admin-app-panel